// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashNoticeController from "./flash_notice_controller"
application.register("flash-notice", FlashNoticeController)

import FormErrorsController from "./form_errors_controller"
application.register("form-errors", FormErrorsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import OnboardingController from "./onboarding_controller"
application.register("onboarding", OnboardingController)
