// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import CartAddController from "./cart_add_controller"
application.register("cart-add", CartAddController)

import CartBadgeController from "./cart_badge_controller"
application.register("cart-badge", CartBadgeController)

import AnimationProductsController from "./animation_products_controller"
application.register("animation-products", AnimationProductsController)

import BannerController from "./banner_controller"
application.register("banner", BannerController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashNoticeController from "./flash_notice_controller"
application.register("flash-notice", FlashNoticeController)

import FormErrorsController from "./form_errors_controller"
application.register("form-errors", FormErrorsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import OnboardingController from "./onboarding_controller"
application.register("onboarding", OnboardingController)
