require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dashboards", type: :request do
  let(:user) { create(:user) }
  let!(:store) { create(:store, user: user) }

  before do
    login_as(user)
  end

  describe "GET /index" do
    it "renders a successful response" do
      get admin_root_url
      expect(response).to be_successful
    end
  end

  describe "GET /dashboard/customize" do
    it "renders a successful response" do
      get admin_customize_url
      expect(response).to be_successful
    end
  end 

  describe "PATCH /dashboard/customize" do
    let(:new_attributes) {
      {
        name: "My Store"
      }
    }
    it "updates the store" do
      patch admin_customize_url, params: { store: new_attributes }
      store.reload
      expect(store.name).to eq("My Store")
    end

    it "redirects to the admin root url" do
      patch admin_customize_url, params: { store: new_attributes }
      expect(response).to redirect_to(admin_root_url)
      expect(flash[:notice]).to eq("Tienda actualizada correctamente.")
    end

    # it "does not update the store" do
    #   let(:new_attributes) {
    #     {
    #       name: "",
    #       description: "My Store",
    #       instagram: "@mystore",
    #       facebook: "@mystore",
    #       whatsapp: "123456789",
    #       primary_color: "#000000"
    #     }
    #   }
    #   patch admin_customize_url, params: { store: new_attributes }
    #   expect(response).to redirect_to(admin_root_url)
    #   expect(store.reload.name).to eq("My Store")
    # end
  end
end
